export const MODEL_CLASSES = ["small", "medium", "large", "unknown"] as const;
export type ModelClass = (typeof MODEL_CLASSES)[number];

export interface Range {
  readonly low: number;
  readonly high: number;
}

export interface ModelClassCoefficients {
  readonly description: string;
  readonly prefillWhPerThousandTokens: Range;
  readonly decodeWhPerThousandTokens: Range;
}

export interface MethodologySource {
  readonly id: string;
  readonly title: string;
  readonly url: string;
  readonly retrievedAt: string;
  readonly usedFor: string;
}

export interface Methodology {
  readonly methodologyVersion: string;
  readonly retrievedAt: string;
  readonly unit: "Wh";
  readonly notice: string;
  readonly sources: readonly MethodologySource[];
  readonly modelClasses: Readonly<Record<ModelClass, ModelClassCoefficients>>;
  readonly infrastructureOverhead: Range & { readonly description: string };
  readonly cacheReadDiscount: Range & { readonly description: string };
}

export interface EstimateInput {
  /** Tokens sent to the model, excluding cache reads. */
  readonly inputTokens: number;
  /** Tokens generated by the model. */
  readonly outputTokens: number;
  /** Tokens served from a prompt cache, when the provider reports them. */
  readonly cachedInputTokens?: number;
  /** Model size class. Omit it rather than guess: `unknown` widens the range. */
  readonly modelClass?: ModelClass;
  /**
   * Grid carbon intensity in grams CO2e per kWh. Without it no carbon figure is
   * produced — LeanRigor will not assume a grid it cannot see.
   */
  readonly gridIntensityGramsPerKwh?: number;
}

export interface CarbonRange {
  readonly low: number;
  readonly central: number;
  readonly high: number;
  readonly unit: "gCO2e";
  readonly gridIntensityGramsPerKwh: number;
}

export interface EstimateRange {
  readonly low: number;
  /**
   * Midpoint of the range. It is a convenience for display, not a best guess:
   * the width of `low`–`high` is the honest content of this estimate.
   */
  readonly central: number;
  readonly high: number;
  readonly unit: "Wh";
  readonly methodologyVersion: string;
  readonly modelClass: ModelClass;
  /** Every assumption that shaped the numbers, in the user's language. */
  readonly assumptions: readonly string[];
  readonly carbon?: CarbonRange;
}
